# Comment out certain settings to use default values.
# For more settings, please refer to the documentation:
# https://bytecodealliance.github.io/wasmtime/cli-cache.html

[cache]
enabled = true
directory = "/Users/klcantrell_mac/dev/try-rust-html/wasm_cache"
